export enum EBookingStatus {
    ASSIGNED = 'ASSIGNED',
    BOOKED = 'BOOKED',
    PICKED_UP = 'PICKED_UP',
    IN_TRANSIT = 'IN_TRANSIT',
    OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
    DELIVERED = 'DELIVERED',
    CANCELLED = 'CANCELLED',
    FAILED_DELIVERY = 'FAILED_DELIVERY',
}
